[package]
name = "azurekvp"
version = "0.1.1"
edition = "2021"
repository = "https://github.com/Azure/azure-init/"
homepage = "https://github.com/Azure/azure-init/"
license = "MIT"
description = "A binary library for implementing OpenTelemetry KVP for Linux VMs on Azure."


[dependencies]
opentelemetry = "0.21"
opentelemetry_sdk = "0.21"
opentelemetry-stdout = { version = "0.2.0", features = ["trace"] }
opentelemetry-otlp = { version = "0.14.0", features = ["default"] }
tracing = "0.1.40"
tracing-opentelemetry = "0.22"
tracing-subscriber = "0.2"
tracing-appender = "0.2"


[[bin]]
name = "azure-kvp"
path = "src/main.rs"