[package]
name = "azurekvp"
version = "0.1.1"
edition = "2021"
repository = "https://github.com/Azure/azure-init/"
homepage = "https://github.com/Azure/azure-init/"
license = "MIT"
description = "A binary library for implementing OpenTelemetry KVP for Linux VMs on Azure."


[dependencies]
opentelemetry = "0.21"
opentelemetry_sdk = "0.21"
opentelemetry-stdout = "0.2.0"
tracing = "0.1"
tracing-opentelemetry = "0.11"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.68"
tracing-subscriber = "0.3"


[[bin]]
name = "azure-kvp"
path = "src/main.rs"