version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "litemap"
        # stay with <= 0.7.4 for Rust 1.76
      - dependency-name: "zerofrom"
        # stay with <= 0.1.5 for Rust 1.76
