version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "assert_cmd"
        # stay with <= 2.0.13 for Rust 1.71
      - dependency-name: "clap"
        # stay with <= 4.4 for Rust 1.71
      - dependency-name: "predicates"
        # stay with <= 3.1.0 for Rust 1.71
      - dependency-name: "predicates-core"
        # stay with <= 1.0.6 for Rust 1.71
      - dependency-name: "predicates-tree"
        # stay with <= 1.0.9 for Rust 1.71
