version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "idna_adapter"
        # stay with <= 1.2.0 for Rust 1.78
      - dependency-name: "sysinfo"
        # stay with <= 0.36 for Rust < 1.85
