// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

//! Unified KVP pool file backend for Hyper-V and Azure guests.
//!
//! All sizes are UTF-8 byte counts — the on-disk pool stores keys and
//! values as zero-padded UTF-8. The Windows-side Hyper-V wire spec is
//! UTF-16 char-based (256 / 1024), but the Linux `hv_kvp_daemon`
//! exchanges UTF-8 bytes with the kernel.
//!
//! Fixed-width record format (matches Linux kernel
//! `HV_KVP_EXCHANGE_MAX_*`):
//! - key field: 512 bytes
//! - value field: 2048 bytes
//! - record size: 2560 bytes
//!
//! [`PoolMode`] selects which size limits are enforced on writes:
//! - [`Safe`](PoolMode::Safe): key <= 254 bytes,
//!   value <= 1022 bytes (recommended for Linux kernel compatibility)
//! - [`Unsafe`](PoolMode::Unsafe): key <= 512 bytes, value <= 2048 bytes
//!
//! ## Reference
//! - [Hyper-V Data Exchange Service (KVP)](https://learn.microsoft.com/en-us/virtualization/hyper-v-on-windows/reference/integration-services#hyper-v-data-exchange-service-kvp)

use std::collections::{HashMap, HashSet};
use std::fs::{File, OpenOptions};
use std::io::{self, ErrorKind, Read, Seek, Write};
use std::os::unix::fs::{MetadataExt, OpenOptionsExt};
use std::os::unix::io::AsRawFd;
use std::path::{Path, PathBuf};

use crate::KvpError;

/// Default base directory for KVP pool files.
const DEFAULT_KVP_DIR: &str = "/var/lib/hyperv";

const WIRE_MAX_KEY_BYTES: usize = 512;
const WIRE_MAX_VALUE_BYTES: usize = 2048;
const SAFE_MAX_KEY_BYTES: usize = 254;
const SAFE_MAX_VALUE_BYTES: usize = 1022;

/// Maximum number of unique keys allowed in the pool.
const MAX_UNIQUE_KEYS: usize = 1024;

const RECORD_SIZE: usize = WIRE_MAX_KEY_BYTES + WIRE_MAX_VALUE_BYTES;

/// Hyper-V KVP pool indices.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
#[repr(u8)]
pub enum KvpPool {
    /// Host-to-guest data pushed by the host admin (`.kvp_pool_0`).
    External = 0,
    /// Guest-to-host data; cloud-init / azure-init write here (`.kvp_pool_1`).
    Guest = 1,
    /// Guest intrinsics generated by the daemon (`.kvp_pool_2`).
    Auto = 2,
    /// Host-originated data describing the host (`.kvp_pool_3`).
    AutoExternal = 3,
    /// Undocumented; no pool file exists (`.kvp_pool_4`).
    AutoInternal = 4,
}

impl KvpPool {
    /// Default base directory for KVP pool files.
    pub fn default_dir() -> &'static Path {
        Path::new(DEFAULT_KVP_DIR)
    }

    /// The conventional on-disk path (`/var/lib/hyperv/<pool_file>`).
    pub fn default_path(self) -> PathBuf {
        Self::default_dir().join(self.file_name())
    }

    /// File name of the pool file, e.g. `.kvp_pool_1`.
    pub fn file_name(self) -> &'static str {
        match self {
            Self::External => ".kvp_pool_0",
            Self::Guest => ".kvp_pool_1",
            Self::Auto => ".kvp_pool_2",
            Self::AutoExternal => ".kvp_pool_3",
            Self::AutoInternal => ".kvp_pool_4",
        }
    }
}

/// Policy mode controlling key/value size limits for writes.
///
/// All limits are **UTF-8 byte counts** measured against the on-disk
/// pool format. The Windows-side Hyper-V wire spec expresses limits
/// in UTF-16 code units (256 / 1024), which equal 512 / 2048 bytes
/// when stored as UTF-8 by `hv_kvp_daemon` on Linux.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum PoolMode {
    /// Conservative limits for Linux kernel compatibility:
    /// key <= 254 UTF-8 bytes, value <= 1022 UTF-8 bytes — 2 bytes
    /// under the kernel `HV_KVP_EXCHANGE_MAX_*` maximums to leave room
    /// for a NUL terminator on either side of the boundary.
    Safe,
    /// Full Hyper-V wire-format limits expressed in UTF-8 bytes:
    /// key <= 512 bytes (== 256 UTF-16 code units),
    /// value <= 2048 bytes (== 1024 UTF-16 code units).
    Unsafe,
}

impl PoolMode {
    fn max_key_size(self) -> usize {
        match self {
            Self::Safe => SAFE_MAX_KEY_BYTES,
            Self::Unsafe => WIRE_MAX_KEY_BYTES,
        }
    }

    fn max_value_size(self) -> usize {
        match self {
            Self::Safe => SAFE_MAX_VALUE_BYTES,
            Self::Unsafe => WIRE_MAX_VALUE_BYTES,
        }
    }
}

/// Unified KVP pool file store.
#[derive(Clone, Debug)]
pub struct KvpPoolStore {
    pool: KvpPool,
    path: PathBuf,
    mode: PoolMode,
}

impl KvpPoolStore {
    /// Append a key-value pair without checking for an existing key.
    pub fn append(&self, key: &str, value: &str) -> Result<(), KvpError> {
        validate_key(key, self.mode.max_key_size())?;
        validate_value(value, self.mode.max_value_size())?;

        {
            let file = self.open_for_read_write_create()?;
            let mut iter = KvpPoolIter::new(file, false)?;
            iter.append(key, value)?;
            iter.flush()?;
        }
        Ok(())
    }

    /// Remove all entries from the store.
    pub fn clear(&self) -> Result<(), KvpError> {
        {
            let file = match self.open_for_read_write() {
                Ok(f) => f,
                Err(ref e) if e.kind() == ErrorKind::NotFound => return Ok(()),
                Err(e) => return Err(e.into()),
            };

            lock_for_writing(&file)?;
            file.set_len(0)?;
        }
        Ok(())
    }

    /// Clear the pool file if it contains data from a previous boot.
    pub fn clear_if_stale(&self) -> Result<(), KvpError> {
        {
            let file = match self.open_for_read_write() {
                Ok(f) => f,
                Err(ref e) if e.kind() == ErrorKind::NotFound => return Ok(()),
                Err(e) => return Err(e.into()),
            };

            let boot_time = boot_time()?;
            lock_for_writing(&file)?;
            if file.metadata()?.mtime() <= boot_time {
                file.set_len(0)?;
            }
        }
        Ok(())
    }

    /// Remove all records matching the key. Returns `true` if at least
    /// one record was present.
    pub fn delete(&self, key: &str) -> Result<bool, KvpError> {
        if key.is_empty() {
            tracing::warn!("Ignoring KVP delete with an empty key");
            return Ok(false);
        }
        if key.as_bytes().contains(&0) {
            tracing::warn!(
                "Ignoring KVP delete with a key containing null bytes"
            );
            return Ok(false);
        }

        let found = {
            let mut iter = match self.iter_mut() {
                Ok(it) => it,
                Err(KvpError::Io(e)) if e.kind() == ErrorKind::NotFound => {
                    return Ok(false);
                }
                Err(e) => return Err(e),
            };

            let mut found = false;
            while let Some(record) = iter.next() {
                let (k, _) = record?;
                if k == key {
                    iter.remove_current()?;
                    found = true;
                }
            }
            if found {
                iter.flush()?;
            }
            found
        };
        Ok(found)
    }

    /// Return all key-value records in on-disk order, including
    /// duplicates from [`append`](Self::append) calls.
    pub fn dump(&self) -> Result<Vec<(String, String)>, KvpError> {
        let records = {
            let mut iter = match self.iter() {
                Ok(it) => it,
                Err(KvpError::Io(e)) if e.kind() == ErrorKind::NotFound => {
                    return Ok(Vec::new());
                }
                Err(e) => return Err(e),
            };

            let mut records = Vec::with_capacity(iter.record_count());
            for record in iter.by_ref() {
                records.push(record?);
            }
            records
        };
        Ok(records)
    }

    /// Return all key-value pairs (deduplicated, last-write-wins).
    pub fn entries(&self) -> Result<HashMap<String, String>, KvpError> {
        let map = {
            let mut iter = match self.iter() {
                Ok(it) => it,
                Err(KvpError::Io(e)) if e.kind() == ErrorKind::NotFound => {
                    return Ok(HashMap::new());
                }
                Err(e) => return Err(e),
            };

            let mut map = HashMap::with_capacity(iter.record_count());
            for record in iter.by_ref() {
                let (k, v) = record?;
                map.insert(k, v);
            }
            map
        };
        Ok(map)
    }

    /// Insert a new key-value pair or update an existing key's value.
    pub fn insert(&self, key: &str, value: &str) -> Result<(), KvpError> {
        validate_key(key, self.mode.max_key_size())?;
        validate_value(value, self.mode.max_value_size())?;

        {
            let file = self.open_for_read_write_create()?;
            let mut iter = KvpPoolIter::new(file, false)?;
            let mut found = false;
            let mut unique_keys = HashSet::new();

            // Continue past the first match to remove any duplicates
            // left by prior `append` calls so the upsert collapses to
            // a single record.
            while let Some(record) = iter.next() {
                let (k, _) = record?;
                let is_target = k == key;
                unique_keys.insert(k);
                if is_target {
                    if !found {
                        iter.overwrite_current_value(value)?;
                        found = true;
                    } else {
                        iter.remove_current()?;
                    }
                }
            }

            if !found {
                if unique_keys.len() >= MAX_UNIQUE_KEYS {
                    return Err(KvpError::MaxUniqueKeysExceeded {
                        max: MAX_UNIQUE_KEYS,
                    });
                }
                iter.append(key, value)?;
            }

            iter.flush()?;
        }
        Ok(())
    }

    /// Return whether the store is empty.
    pub fn is_empty(&self) -> Result<bool, KvpError> {
        Ok(self.len()? == 0)
    }

    /// Whether the store's data is stale (e.g. predates current boot).
    pub fn is_stale(&self) -> Result<bool, KvpError> {
        let metadata = match std::fs::metadata(&self.path) {
            Ok(m) => m,
            Err(ref e) if e.kind() == ErrorKind::NotFound => return Ok(false),
            Err(e) => return Err(e.into()),
        };
        Ok(metadata.mtime() <= boot_time()?)
    }

    /// Variant of [`is_stale`](Self::is_stale) that takes an explicit
    /// boot time, allowing tests to assert against a deterministic
    /// reference point.
    #[cfg(test)]
    fn is_stale_at_boot(&self, boot_time: i64) -> Result<bool, KvpError> {
        let metadata = match std::fs::metadata(&self.path) {
            Ok(m) => m,
            Err(ref e) if e.kind() == ErrorKind::NotFound => return Ok(false),
            Err(e) => return Err(e.into()),
        };
        Ok(metadata.mtime() <= boot_time)
    }

    fn iter(&self) -> Result<KvpPoolIter, KvpError> {
        let file = self.open_for_read()?;
        KvpPoolIter::new(file, true)
    }

    fn iter_mut(&self) -> Result<KvpPoolIter, KvpError> {
        let file = self.open_for_read_write()?;
        KvpPoolIter::new(file, false)
    }

    /// Return the number of records in the store.
    ///
    /// This counts on-disk records, not unique keys. If
    /// [`append`](Self::append) was used to write duplicate keys, this
    /// may exceed the number of unique keys returned by
    /// [`entries`](Self::entries).
    pub fn len(&self) -> Result<usize, KvpError> {
        match std::fs::metadata(&self.path) {
            Ok(m) => {
                record_count_from_len(m.len() as usize).map_err(Into::into)
            }
            Err(ref e) if e.kind() == ErrorKind::NotFound => Ok(0),
            Err(e) => Err(e.into()),
        }
    }

    /// Maximum key size in bytes for writes.
    pub fn max_key_size(&self) -> usize {
        self.mode.max_key_size()
    }

    /// Maximum value size in bytes for writes.
    pub fn max_value_size(&self) -> usize {
        self.mode.max_value_size()
    }

    /// The policy mode this store was created with.
    pub fn mode(&self) -> PoolMode {
        self.mode
    }

    /// Open using the default Hyper-V directory
    /// ([`/var/lib/hyperv`](KvpPool::default_dir)).
    pub fn new(pool: KvpPool, mode: PoolMode) -> Result<Self, KvpError> {
        Self::new_in(pool, KvpPool::default_dir(), mode)
    }

    /// Open using a custom directory (file name derived from `pool`).
    pub fn new_in(
        pool: KvpPool,
        dir: impl AsRef<Path>,
        mode: PoolMode,
    ) -> Result<Self, KvpError> {
        let path = dir.as_ref().join(pool.file_name());
        Ok(Self { pool, path, mode })
    }

    fn open_for_read(&self) -> io::Result<File> {
        OpenOptions::new().read(true).open(&self.path)
    }

    fn open_for_read_write(&self) -> io::Result<File> {
        OpenOptions::new().read(true).write(true).open(&self.path)
    }

    fn open_for_read_write_create(&self) -> io::Result<File> {
        OpenOptions::new()
            .read(true)
            .write(true)
            .create(true)
            .truncate(false)
            .mode(0o600)
            .open(&self.path)
    }

    /// Return a reference to the pool file path.
    pub fn path(&self) -> &Path {
        &self.path
    }

    /// The pool this store was created for.
    pub fn pool(&self) -> KvpPool {
        self.pool
    }

    /// Atomically replace all records with the given pairs, in
    /// iteration order. Inverse of [`dump`](Self::dump): duplicates
    /// are preserved, but unique-key count is capped at
    /// [`MAX_UNIQUE_KEYS`].
    ///
    /// Validation happens before locking, so a rejected batch never
    /// blocks other writers. The file is truncated and rewritten
    /// under one exclusive lock; an I/O error mid-write may leave
    /// the file partially written. Every successful call updates
    /// mtime (relevant to [`is_stale`](Self::is_stale)). Rejects
    /// malformed pool files (size not a multiple of the record
    /// size); call [`clear`](Self::clear) first to recover.
    pub fn populate<I, K, V>(&self, records: I) -> Result<(), KvpError>
    where
        I: IntoIterator<Item = (K, V)>,
        K: Into<String>,
        V: Into<String>,
    {
        let records: Vec<(String, String)> = records
            .into_iter()
            .map(|(k, v)| (k.into(), v.into()))
            .collect();

        let max_key = self.mode.max_key_size();
        let max_value = self.mode.max_value_size();
        let mut unique_keys = HashSet::new();
        for (k, v) in &records {
            validate_key(k, max_key)?;
            validate_value(v, max_value)?;
            unique_keys.insert(k.as_str());
        }
        if unique_keys.len() > MAX_UNIQUE_KEYS {
            return Err(KvpError::MaxUniqueKeysExceeded {
                max: MAX_UNIQUE_KEYS,
            });
        }

        {
            let file = self.open_for_read_write_create()?;
            let mut iter = KvpPoolIter::new(file, false)?;
            iter.file.set_len(0)?;
            iter.record_count = 0;
            for (k, v) in &records {
                iter.append(k, v)?;
            }
            iter.flush()?;
        }
        Ok(())
    }

    /// Read the value for a key. Returns `Ok(None)` when absent.
    ///
    /// If multiple records share the same key (e.g. via
    /// [`append`](Self::append)), the last (most recent) match wins.
    ///
    /// Unlike write operations, `read` does **not** enforce
    /// [`PoolMode`] key-size limits, so a [`Safe`](PoolMode::Safe)-mode
    /// store can read keys that were written in
    /// [`Unsafe`](PoolMode::Unsafe) mode.
    pub fn read(&self, key: &str) -> Result<Option<String>, KvpError> {
        if key.is_empty() {
            tracing::warn!("Ignoring KVP read with an empty key");
            return Ok(None);
        }
        if key.as_bytes().contains(&0) {
            tracing::warn!(
                "Ignoring KVP read with a key containing null bytes"
            );
            return Ok(None);
        }

        let result = {
            let mut iter = match self.iter() {
                Ok(it) => it,
                Err(KvpError::Io(e)) if e.kind() == ErrorKind::NotFound => {
                    return Ok(None);
                }
                Err(e) => return Err(e),
            };

            let mut result = None;
            for record in iter.by_ref() {
                let (k, v) = record?;
                if k == key {
                    result = Some(v);
                }
            }
            result
        };
        Ok(result)
    }
}

fn boot_time() -> Result<i64, KvpError> {
    parse_proc_stat_btime(&std::fs::read_to_string("/proc/stat")?)
        .map_err(Into::into)
}

fn parse_proc_stat_btime(contents: &str) -> io::Result<i64> {
    for line in contents.lines() {
        if let Some(value) = line.strip_prefix("btime ") {
            return value.trim().parse::<i64>().map_err(|e| {
                io::Error::new(
                    ErrorKind::InvalidData,
                    format!("invalid /proc/stat btime value: {e}"),
                )
            });
        }
    }

    Err(io::Error::new(
        ErrorKind::NotFound,
        "missing btime in /proc/stat",
    ))
}

fn record_count_from_len(len: usize) -> io::Result<usize> {
    if len > 0 && !len.is_multiple_of(RECORD_SIZE) {
        return Err(io::Error::other(format!(
            "file size ({len}) is not a multiple of record size \
             ({RECORD_SIZE})"
        )));
    }
    Ok(len / RECORD_SIZE)
}

fn decode_record(data: &[u8]) -> io::Result<(String, String)> {
    if data.len() != RECORD_SIZE {
        return Err(io::Error::other(format!(
            "record size mismatch: expected {RECORD_SIZE}, got {}",
            data.len()
        )));
    }

    let (key_bytes, value_bytes) = data.split_at(WIRE_MAX_KEY_BYTES);

    let key = std::str::from_utf8(key_bytes)
        .map_err(|e| io::Error::new(ErrorKind::InvalidData, e))?
        .trim_end_matches('\0')
        .to_string();
    let value = std::str::from_utf8(value_bytes)
        .map_err(|e| io::Error::new(ErrorKind::InvalidData, e))?
        .trim_end_matches('\0')
        .to_string();

    Ok((key, value))
}

fn encode_record(key: &str, value: &str) -> Vec<u8> {
    let mut buf = vec![0u8; RECORD_SIZE];

    let key_bytes = key.as_bytes();
    let key_len = key_bytes.len().min(WIRE_MAX_KEY_BYTES);
    buf[..key_len].copy_from_slice(&key_bytes[..key_len]);

    let value_bytes = value.as_bytes();
    let value_len = value_bytes.len().min(WIRE_MAX_VALUE_BYTES);
    buf[WIRE_MAX_KEY_BYTES..WIRE_MAX_KEY_BYTES + value_len]
        .copy_from_slice(&value_bytes[..value_len]);

    buf
}

// Locking: on Linux, take both `flock` and `fcntl` OFD locks together.
//
// Linux's `flock(2)` and `fcntl(2)` byte-range locks live in disjoint
// kernel domains. `hv_kvp_daemon` uses `fcntl`; cloud-init uses
// `flock(LOCK_EX)`. Hold both to coordinate with either.
//
// Acquire `flock` first. Successful locks are released when the file
// descriptor closes. The `fcntl` OFD variant (`F_OFD_SETLKW`) shares a
// domain with classic POSIX `fcntl` byte-range locks but is per-fd and
// thread-safe.
//

/// `flock(LOCK_EX)` then `fcntl(F_WRLCK)`. If `fcntl` fails, the
/// `flock` is released before returning the error.
fn lock_for_writing(file: &File) -> io::Result<()> {
    flock_lock_exclusive(file)?;
    if let Err(e) = fcntl_lock_exclusive(file) {
        let _ = flock_unlock(file);
        return Err(e);
    }
    Ok(())
}

/// `flock(LOCK_SH)` then `fcntl(F_RDLCK)`. See [`lock_for_writing`]
/// for the all-or-nothing semantics.
fn lock_for_reading(file: &File) -> io::Result<()> {
    flock_lock_shared(file)?;
    if let Err(e) = fcntl_lock_shared(file) {
        let _ = flock_unlock(file);
        return Err(e);
    }
    Ok(())
}

/// Acquire an exclusive (write) `fcntl` OFD lock on the entire file.
fn fcntl_lock_exclusive(file: &File) -> io::Result<()> {
    let fl = libc::flock {
        l_type: libc::F_WRLCK as libc::c_short,
        l_whence: libc::SEEK_SET as libc::c_short,
        l_start: 0,
        l_len: 0,
        l_pid: 0,
    };
    if unsafe { libc::fcntl(file.as_raw_fd(), libc::F_OFD_SETLKW, &fl) } == -1 {
        return Err(io::Error::other(format!(
            "failed to fcntl-lock KVP file: {}",
            io::Error::last_os_error()
        )));
    }
    Ok(())
}

/// Acquire a shared (read) `fcntl` OFD lock on the entire file.
fn fcntl_lock_shared(file: &File) -> io::Result<()> {
    let fl = libc::flock {
        l_type: libc::F_RDLCK as libc::c_short,
        l_whence: libc::SEEK_SET as libc::c_short,
        l_start: 0,
        l_len: 0,
        l_pid: 0,
    };
    if unsafe { libc::fcntl(file.as_raw_fd(), libc::F_OFD_SETLKW, &fl) } == -1 {
        return Err(io::Error::other(format!(
            "failed to fcntl-lock KVP file: {}",
            io::Error::last_os_error()
        )));
    }
    Ok(())
}

/// Acquire a `flock(LOCK_EX)` exclusive lock on the entire file.
fn flock_lock_exclusive(file: &File) -> io::Result<()> {
    if unsafe { libc::flock(file.as_raw_fd(), libc::LOCK_EX) } == -1 {
        return Err(io::Error::other(format!(
            "failed to flock KVP file: {}",
            io::Error::last_os_error()
        )));
    }
    Ok(())
}

/// Acquire a `flock(LOCK_SH)` shared lock on the entire file.
fn flock_lock_shared(file: &File) -> io::Result<()> {
    if unsafe { libc::flock(file.as_raw_fd(), libc::LOCK_SH) } == -1 {
        return Err(io::Error::other(format!(
            "failed to flock KVP file: {}",
            io::Error::last_os_error()
        )));
    }
    Ok(())
}

/// Release the `flock` lock on the entire file.
fn flock_unlock(file: &File) -> io::Result<()> {
    if unsafe { libc::flock(file.as_raw_fd(), libc::LOCK_UN) } == -1 {
        return Err(io::Error::other(format!(
            "failed to flock-unlock KVP file: {}",
            io::Error::last_os_error()
        )));
    }
    Ok(())
}

fn validate_key(key: &str, max: usize) -> Result<(), KvpError> {
    if key.is_empty() {
        return Err(KvpError::EmptyKey);
    }
    if key.as_bytes().contains(&0) {
        return Err(KvpError::KeyContainsNull);
    }
    let actual = key.len();
    if actual > max {
        return Err(KvpError::KeyTooLarge { max, actual });
    }
    Ok(())
}

fn validate_value(value: &str, max: usize) -> Result<(), KvpError> {
    if value.as_bytes().contains(&0) {
        return Err(KvpError::ValueContainsNull);
    }
    let actual = value.len();
    if actual > max {
        return Err(KvpError::ValueTooLarge { max, actual });
    }
    Ok(())
}

/// A record-at-a-time iterator over a KVP pool file.
///
/// Uses file I/O with seek semantics for memory-efficient iteration
/// without loading all records into memory. Supports in-place value
/// overwrites and record removal for the last-yielded record.
///
/// The underlying file is locked in [`new`](Self::new). Locks are held
/// for the iterator's lifetime and released when the iterator's file
/// descriptor is dropped.
#[derive(Debug)]
struct KvpPoolIter {
    file: File,
    record_count: usize,
    current_index: usize,
}

impl KvpPoolIter {
    /// Append a new record at the end of the file, zero-padded to the
    /// fixed-width wire format.
    fn append(&mut self, key: &str, value: &str) -> io::Result<()> {
        let resume_pos = self.file.stream_position()?;
        let pos = self.file.seek(io::SeekFrom::End(0))?;
        debug_assert!((pos as usize).is_multiple_of(RECORD_SIZE));
        self.file.write_all(&encode_record(key, value))?;
        self.record_count += 1;
        self.file.seek(io::SeekFrom::Start(resume_pos))?;
        Ok(())
    }

    /// Flush any buffered writes to the underlying file.
    fn flush(&mut self) -> io::Result<()> {
        self.file.flush()
    }

    fn new(mut file: File, read_only: bool) -> Result<Self, KvpError> {
        if read_only {
            lock_for_reading(&file)?;
        } else {
            lock_for_writing(&file)?;
        }

        let record_count =
            record_count_from_len(file.metadata()?.len() as usize)?;
        file.seek(io::SeekFrom::Start(0))?;

        Ok(Self {
            file,
            record_count,
            current_index: 0,
        })
    }

    /// Overwrite the value field of the record last returned by
    /// [`next()`](Iterator::next), zero-padding to fill the
    /// fixed-width 2048-byte field.
    ///
    /// After the write the file position is at the start of the next
    /// record, so iteration can continue normally.
    ///
    /// Returns `InvalidInput` if called before the first `next()`.
    fn overwrite_current_value(&mut self, value: &str) -> io::Result<()> {
        if self.current_index == 0 {
            return Err(io::Error::new(
                ErrorKind::InvalidInput,
                "no record has been read yet",
            ));
        }

        let record_start = (self.current_index - 1) as u64 * RECORD_SIZE as u64;
        let value_offset = record_start + WIRE_MAX_KEY_BYTES as u64;

        self.file.seek(io::SeekFrom::Start(value_offset))?;

        let mut buf = [0u8; WIRE_MAX_VALUE_BYTES];
        let bytes = value.as_bytes();
        let len = bytes.len().min(WIRE_MAX_VALUE_BYTES);
        buf[..len].copy_from_slice(&bytes[..len]);

        self.file.write_all(&buf)?;
        Ok(())
    }

    /// The number of records in the file (updated by
    /// [`append`](Self::append) and
    /// [`remove_current`](Self::remove_current)).
    fn record_count(&self) -> usize {
        self.record_count
    }

    /// Remove the record last returned by [`next()`](Iterator::next)
    /// by swapping it with the final record and truncating the file.
    ///
    /// After removal the file position rewinds so that the next call
    /// to `next()` reads the record that was swapped into this slot
    /// (unless the removed record was already the last one).
    ///
    /// Returns `InvalidInput` if called before the first `next()`.
    fn remove_current(&mut self) -> io::Result<()> {
        if self.current_index == 0 {
            return Err(io::Error::new(
                ErrorKind::InvalidInput,
                "no record has been read yet",
            ));
        }

        let delete_index = self.current_index - 1;
        let last_index = self.record_count - 1;

        if delete_index != last_index {
            self.file.seek(io::SeekFrom::Start(
                last_index as u64 * RECORD_SIZE as u64,
            ))?;
            let mut buf = [0u8; RECORD_SIZE];
            self.file.read_exact(&mut buf)?;

            self.file.seek(io::SeekFrom::Start(
                delete_index as u64 * RECORD_SIZE as u64,
            ))?;
            self.file.write_all(&buf)?;

            // Rewind so the next `next()` re-reads `delete_index`,
            // which now holds the swapped-in record. `write_all`
            // advanced the cursor past it, hence this third seek.
            self.file.seek(io::SeekFrom::Start(
                delete_index as u64 * RECORD_SIZE as u64,
            ))?;
            self.current_index = delete_index;
        }
        // No-swap branch: `current_index` is left at the old
        // `record_count`, so after the truncate below the iterator
        // is naturally exhausted and the next `next()` returns None.

        self.file.set_len(last_index as u64 * RECORD_SIZE as u64)?;
        self.record_count -= 1;
        Ok(())
    }
}

impl Iterator for KvpPoolIter {
    type Item = io::Result<(String, String)>;

    fn next(&mut self) -> Option<Self::Item> {
        if self.current_index >= self.record_count {
            return None;
        }
        let mut buf = [0u8; RECORD_SIZE];
        match self.file.read_exact(&mut buf) {
            Ok(()) => {
                self.current_index += 1;
                Some(decode_record(&buf))
            }
            Err(e) => Some(Err(e)),
        }
    }

    fn size_hint(&self) -> (usize, Option<usize>) {
        let remaining = self.record_count - self.current_index;
        (remaining, Some(remaining))
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use rstest::rstest;
    use std::error::Error;
    use std::os::unix::fs::PermissionsExt;
    use tempfile::{NamedTempFile, TempDir};

    fn safe_store(dir: &Path) -> KvpPoolStore {
        KvpPoolStore::new_in(KvpPool::Guest, dir, PoolMode::Safe).unwrap()
    }

    fn unsafe_store(dir: &Path) -> KvpPoolStore {
        KvpPoolStore::new_in(KvpPool::Guest, dir, PoolMode::Unsafe).unwrap()
    }

    /// `&str` literals → `Vec<(String, String)>` for `dump`/`populate`.
    fn pairs<const N: usize>(
        items: [(&str, &str); N],
    ) -> Vec<(String, String)> {
        items
            .iter()
            .map(|(k, v)| (k.to_string(), v.to_string()))
            .collect()
    }

    /// Bulk-load `count` records (`k0..k{count-1}` → `"v"`) for tests
    /// that need to set up at or near [`MAX_UNIQUE_KEYS`].
    fn prepopulate(store: &KvpPoolStore, count: usize) {
        let records: Vec<(String, String)> = (0..count)
            .map(|i| (format!("k{i}"), "v".to_string()))
            .collect();
        store.populate(records).unwrap();
    }

    fn lock_dir(dir: &Path) {
        std::fs::set_permissions(dir, std::fs::Permissions::from_mode(0o000))
            .unwrap();
    }

    fn unlock_dir(dir: &Path) {
        std::fs::set_permissions(dir, std::fs::Permissions::from_mode(0o755))
            .unwrap();
    }

    fn set_mtime_to_epoch(path: &Path) {
        let c_path =
            std::ffi::CString::new(path.as_os_str().as_encoded_bytes())
                .unwrap();
        let times = [libc::timeval {
            tv_sec: 0,
            tv_usec: 0,
        }; 2];
        assert_eq!(unsafe { libc::utimes(c_path.as_ptr(), times.as_ptr()) }, 0);
    }

    fn make_fifo_at(path: &Path) {
        let c_path =
            std::ffi::CString::new(path.as_os_str().as_encoded_bytes())
                .unwrap();
        assert_eq!(unsafe { libc::mkfifo(c_path.as_ptr(), 0o644) }, 0);
    }

    #[test]
    fn test_kvp_pool_file_names() {
        assert_eq!(KvpPool::External.file_name(), ".kvp_pool_0");
        assert_eq!(KvpPool::Guest.file_name(), ".kvp_pool_1");
        assert_eq!(KvpPool::Auto.file_name(), ".kvp_pool_2");
        assert_eq!(KvpPool::AutoExternal.file_name(), ".kvp_pool_3");
        assert_eq!(KvpPool::AutoInternal.file_name(), ".kvp_pool_4");
    }

    #[test]
    fn test_kvp_pool_default_dir_and_path() {
        assert_eq!(KvpPool::default_dir(), Path::new("/var/lib/hyperv"));
        assert_eq!(
            KvpPool::Guest.default_path(),
            Path::new("/var/lib/hyperv/.kvp_pool_1")
        );
    }

    #[test]
    fn test_default_path_is_used() {
        let store = KvpPoolStore::new(KvpPool::Guest, PoolMode::Safe).unwrap();
        assert_eq!(store.path(), KvpPool::Guest.default_path());
    }

    #[test]
    fn test_new_in_derives_path_from_pool() {
        let dir = TempDir::new().unwrap();
        let store =
            KvpPoolStore::new_in(KvpPool::Guest, dir.path(), PoolMode::Safe)
                .unwrap();
        assert_eq!(store.path(), dir.path().join(KvpPool::Guest.file_name()));
    }

    #[test]
    fn test_pool_getter() {
        let store =
            KvpPoolStore::new(KvpPool::External, PoolMode::Safe).unwrap();
        assert_eq!(store.pool(), KvpPool::External);
    }

    #[test]
    fn test_mode_getter() {
        let dir = TempDir::new().unwrap();
        let store_safe = safe_store(dir.path());
        assert_eq!(store_safe.mode(), PoolMode::Safe);

        let dir2 = TempDir::new().unwrap();
        let store_unsafe = unsafe_store(dir2.path());
        assert_eq!(store_unsafe.mode(), PoolMode::Unsafe);
    }

    #[rstest]
    #[case::safe_key(PoolMode::Safe, Field::Key, 254)]
    #[case::safe_value(PoolMode::Safe, Field::Value, 1022)]
    #[case::unsafe_key(PoolMode::Unsafe, Field::Key, 512)]
    #[case::unsafe_value(PoolMode::Unsafe, Field::Value, 2048)]
    fn test_max_size_getters(
        #[case] mode: PoolMode,
        #[case] field: Field,
        #[case] expected: usize,
    ) {
        let dir = TempDir::new().unwrap();
        let store =
            KvpPoolStore::new_in(KvpPool::Guest, dir.path(), mode).unwrap();
        let actual = match field {
            Field::Key => store.max_key_size(),
            Field::Value => store.max_value_size(),
        };
        assert_eq!(actual, expected);
    }

    /// Every write op rejects empty keys, null bytes in keys, and null
    /// bytes in values with the matching variant of [`KvpError`].
    #[rstest]
    #[case::insert_empty_key(WriteOp::Insert, "", "v", KvpErrKind::EmptyKey)]
    #[case::insert_null_key(
        WriteOp::Insert, "bad\0key", "v", KvpErrKind::KeyContainsNull
    )]
    #[case::insert_null_value(
        WriteOp::Insert, "k", "bad\0value", KvpErrKind::ValueContainsNull
    )]
    #[case::append_null_value(
        WriteOp::Append, "k", "bad\0value", KvpErrKind::ValueContainsNull
    )]
    #[case::populate_empty_key(
        WriteOp::Populate, "", "v", KvpErrKind::EmptyKey
    )]
    fn test_write_rejects_invalid_input(
        #[case] op: WriteOp,
        #[case] key: &str,
        #[case] value: &str,
        #[case] expected: KvpErrKind,
    ) {
        let dir = TempDir::new().unwrap();
        let store = safe_store(dir.path());
        let err = match op {
            WriteOp::Insert => store.insert(key, value),
            WriteOp::Append => store.append(key, value),
            WriteOp::Populate => store.populate(pairs([(key, value)])),
        }
        .unwrap_err();
        assert!(expected.matches(&err), "got: {err:?}");
    }

    #[derive(Clone, Copy)]
    enum Field {
        Key,
        Value,
    }

    #[derive(Clone, Copy)]
    enum Op {
        Insert,
        Append,
    }

    #[derive(Clone, Copy)]
    enum WriteOp {
        Insert,
        Append,
        Populate,
    }

    #[derive(Clone, Copy)]
    enum FifoOp {
        Clear,
        Append,
        Populate,
    }

    /// Discriminant tag for the [`KvpError`] variants asserted by
    /// parametrized tests. Cases use one tag per variant so the test
    /// only needs to compare discriminants, not pattern-match.
    #[derive(Clone, Copy, Debug, PartialEq, Eq)]
    enum KvpErrKind {
        EmptyKey,
        KeyContainsNull,
        ValueContainsNull,
    }

    impl KvpErrKind {
        fn matches(self, err: &KvpError) -> bool {
            matches!(
                (self, err),
                (Self::EmptyKey, KvpError::EmptyKey)
                    | (Self::KeyContainsNull, KvpError::KeyContainsNull)
                    | (Self::ValueContainsNull, KvpError::ValueContainsNull)
            )
        }
    }

    /// For each `(PoolMode, Op, Field)`, accept `max` and reject `max + 1`.
    #[rstest]
    #[case::safe_insert_key(PoolMode::Safe, Op::Insert, Field::Key, 254)]
    #[case::safe_insert_value(PoolMode::Safe, Op::Insert, Field::Value, 1022)]
    #[case::safe_append_key(PoolMode::Safe, Op::Append, Field::Key, 254)]
    #[case::safe_append_value(PoolMode::Safe, Op::Append, Field::Value, 1022)]
    #[case::unsafe_insert_key(PoolMode::Unsafe, Op::Insert, Field::Key, 512)]
    #[case::unsafe_insert_value(
        PoolMode::Unsafe,
        Op::Insert,
        Field::Value,
        2048
    )]
    #[case::unsafe_append_key(PoolMode::Unsafe, Op::Append, Field::Key, 512)]
    #[case::unsafe_append_value(
        PoolMode::Unsafe,
        Op::Append,
        Field::Value,
        2048
    )]
    fn test_size_limits(
        #[case] mode: PoolMode,
        #[case] op: Op,
        #[case] field: Field,
        #[case] max: usize,
    ) {
        let dir = TempDir::new().unwrap();
        let store =
            KvpPoolStore::new_in(KvpPool::Guest, dir.path(), mode).unwrap();

        let write = |store: &KvpPoolStore, k: &str, v: &str| match op {
            Op::Insert => store.insert(k, v),
            Op::Append => store.append(k, v),
        };

        match field {
            Field::Key => {
                write(&store, &"k".repeat(max), "v").unwrap();
                let err = write(&store, &"k".repeat(max + 1), "v").unwrap_err();
                assert!(matches!(err, KvpError::KeyTooLarge { .. }));
            }
            Field::Value => {
                write(&store, "k", &"v".repeat(max)).unwrap();
                let err =
                    write(&store, "k2", &"v".repeat(max + 1)).unwrap_err();
                assert!(matches!(err, KvpError::ValueTooLarge { .. }));
            }
        }
    }

    #[test]
    fn test_read_accepts_wire_max_key_in_safe_mode() {
        let dir = TempDir::new().unwrap();
        let store = safe_store(dir.path());

        let store_unsafe = unsafe_store(dir.path());
        let long_key = "k".repeat(300);
        store_unsafe.insert(&long_key, "val").unwrap();

        assert_eq!(store.read(&long_key).unwrap(), Some("val".to_string()));

        let too_long = "k".repeat(513);
        assert_eq!(store.read(&too_long).unwrap(), None);
    }

    #[test]
    fn test_insert_overwrites_existing_key() {
        let dir = TempDir::new().unwrap();
        let store = safe_store(dir.path());

        store
            .populate(pairs([("key", "v1"), ("other", "v3")]))
            .unwrap();
        store.insert("key", "v2").unwrap();

        assert_eq!(
            store.dump().unwrap(),
            pairs([("key", "v2"), ("other", "v3")])
        );
    }

    #[rstest]
    #[case::overwrite_same_size("key", "original", "key", "updated", 0)]
    #[case::new_key_grows_one_record("k1", "v1", "k2", "v2", RECORD_SIZE as i64)]
    fn test_insert_file_size_delta(
        #[case] k1: &str,
        #[case] v1: &str,
        #[case] k2: &str,
        #[case] v2: &str,
        #[case] expected_delta: i64,
    ) {
        let dir = TempDir::new().unwrap();
        let store = safe_store(dir.path());

        store.insert(k1, v1).unwrap();
        let before = std::fs::metadata(store.path()).unwrap().len() as i64;
        store.insert(k2, v2).unwrap();
        let after = std::fs::metadata(store.path()).unwrap().len() as i64;

        assert_eq!(after - before, expected_delta);
    }

    #[test]
    fn test_insert_preserves_other_records() {
        let dir = TempDir::new().unwrap();
        let store = safe_store(dir.path());

        for i in 0..5 {
            store.insert(&format!("k{i}"), &format!("v{i}")).unwrap();
        }

        let raw_before = std::fs::read(store.path()).unwrap();
        store.insert("k2", "CHANGED").unwrap();
        let raw_after = std::fs::read(store.path()).unwrap();

        assert_eq!(raw_before.len(), raw_after.len());
        for i in 0..5 {
            if i == 2 {
                continue;
            }
            let start = i * RECORD_SIZE;
            let end = start + RECORD_SIZE;
            assert_eq!(&raw_before[start..end], &raw_after[start..end]);
        }
    }

    #[test]
    fn test_insert_after_append_duplicates_collapses_to_one() {
        let dir = TempDir::new().unwrap();
        let store = safe_store(dir.path());

        store
            .populate(pairs([("k", "v1"), ("k", "v2"), ("k", "v3")]))
            .unwrap();

        store.insert("k", "updated").unwrap();
        assert_eq!(store.dump().unwrap(), pairs([("k", "updated")]));
    }

    #[test]
    fn test_unique_key_cap_allows_1024_then_rejects_1025th() {
        let dir = TempDir::new().unwrap();
        let store = safe_store(dir.path());

        prepopulate(&store, MAX_UNIQUE_KEYS);
        assert_eq!(store.len().unwrap(), MAX_UNIQUE_KEYS);

        let err = store.insert("overflow", "v").unwrap_err();
        assert!(matches!(err, KvpError::MaxUniqueKeysExceeded { .. }));
    }

    #[test]
    fn test_unique_key_cap_allows_overwrite_at_limit() {
        let dir = TempDir::new().unwrap();
        let store = safe_store(dir.path());

        prepopulate(&store, MAX_UNIQUE_KEYS);

        store.insert("k0", "updated").unwrap();
        assert_eq!(store.read("k0").unwrap(), Some("updated".to_string()));
    }

    #[test]
    fn test_insert_cap_uses_unique_keys_not_record_count() {
        let dir = TempDir::new().unwrap();
        let store = safe_store(dir.path());

        prepopulate(&store, MAX_UNIQUE_KEYS - 1);

        store.append("k0", "dup").unwrap();
        assert_eq!(store.len().unwrap(), MAX_UNIQUE_KEYS);

        store.insert("new_unique", "v").unwrap();
        assert_eq!(store.read("new_unique").unwrap(), Some("v".to_string()));
    }

    #[test]
    fn test_unique_key_cap_allows_new_key_after_delete() {
        let dir = TempDir::new().unwrap();
        let store = safe_store(dir.path());

        prepopulate(&store, MAX_UNIQUE_KEYS);

        assert!(store.delete("k0").unwrap());
        store.insert("new-key", "v").unwrap();
    }

    #[test]
    fn test_append_no_key_cap() {
        let dir = TempDir::new().unwrap();
        let store = safe_store(dir.path());

        prepopulate(&store, MAX_UNIQUE_KEYS);

        store.append("extra", "val").unwrap();
        assert_eq!(store.len().unwrap(), MAX_UNIQUE_KEYS + 1);
    }

    #[test]
    fn test_append_then_read() {
        let dir = TempDir::new().unwrap();
        let store = safe_store(dir.path());

        store.append("diag_001", "event_data").unwrap();
        assert_eq!(
            store.read("diag_001").unwrap(),
            Some("event_data".to_string())
        );
    }

    #[test]
    fn test_created_pool_file_mode_is_private() {
        let dir = TempDir::new().unwrap();
        let store = safe_store(dir.path());

        store.append("key", "value").unwrap();

        let mode = std::fs::metadata(store.path())
            .unwrap()
            .permissions()
            .mode()
            & 0o777;
        assert_eq!(mode, 0o600);
    }

    #[test]
    fn test_append_duplicate_key_semantics() {
        let dir = TempDir::new().unwrap();
        let store = safe_store(dir.path());

        store.append("X", "first").unwrap();
        store.append("X", "second").unwrap();

        assert_eq!(
            store.dump().unwrap(),
            pairs([("X", "first"), ("X", "second")])
        );
        assert_eq!(store.read("X").unwrap(), Some("second".to_string()));
    }

    /// Every store op tolerates a missing pool file by returning a
    /// well-defined sentinel result instead of erroring.
    #[rstest]
    #[case::read(StoreOp::Read)]
    #[case::delete(StoreOp::Delete)]
    #[case::clear(StoreOp::Clear)]
    #[case::clear_if_stale(StoreOp::ClearIfStale)]
    #[case::entries(StoreOp::Entries)]
    #[case::dump(StoreOp::Dump)]
    #[case::len(StoreOp::Len)]
    #[case::is_stale(StoreOp::IsStale)]
    #[case::is_stale_at_boot(StoreOp::IsStaleAtBoot)]
    fn test_missing_file_is_ok(#[case] op: StoreOp) {
        let dir = TempDir::new().unwrap();
        let store = safe_store(dir.path());

        match op {
            StoreOp::Read => assert_eq!(store.read("k").unwrap(), None),
            StoreOp::Delete => assert!(!store.delete("k").unwrap()),
            StoreOp::Clear => store.clear().unwrap(),
            StoreOp::ClearIfStale => store.clear_if_stale().unwrap(),
            StoreOp::Entries => {
                assert!(store.entries().unwrap().is_empty());
            }
            StoreOp::Dump => assert!(store.dump().unwrap().is_empty()),
            StoreOp::Len => assert_eq!(store.len().unwrap(), 0),
            StoreOp::IsStale => assert!(!store.is_stale().unwrap()),
            StoreOp::IsStaleAtBoot => {
                assert!(!store.is_stale_at_boot(i64::MAX).unwrap());
            }
            StoreOp::Populate | StoreOp::Insert | StoreOp::Append => {
                unreachable!("write ops not in this test's case list")
            }
        }
        assert!(!store.path().exists());
    }

    /// Bad keys (empty, contains null) are silently no-ops on read/delete:
    /// they return the absent sentinel and leave existing data untouched.
    #[rstest]
    #[case::read_empty(ReadOp::Read, "")]
    #[case::read_null(ReadOp::Read, "bad\0key")]
    #[case::delete_empty(ReadOp::Delete, "")]
    #[case::delete_null(ReadOp::Delete, "bad\0key")]
    fn test_bad_key_is_silent_noop(#[case] op: ReadOp, #[case] bad_key: &str) {
        let dir = TempDir::new().unwrap();
        let store = safe_store(dir.path());
        store.insert("k1", "v1").unwrap();

        match op {
            ReadOp::Read => assert_eq!(store.read(bad_key).unwrap(), None),
            ReadOp::Delete => assert!(!store.delete(bad_key).unwrap()),
        }
        assert_eq!(store.read("k1").unwrap(), Some("v1".to_string()));
        assert_eq!(store.len().unwrap(), 1);
    }

    #[derive(Clone, Copy)]
    enum ReadOp {
        Read,
        Delete,
    }

    #[test]
    fn test_delete_removes_key() {
        let dir = TempDir::new().unwrap();
        let store = safe_store(dir.path());

        store
            .populate(pairs([("key", "v1"), ("other", "v2")]))
            .unwrap();

        assert!(store.delete("key").unwrap());
        assert_eq!(store.dump().unwrap(), pairs([("other", "v2")]));
    }

    #[test]
    fn test_delete_removes_all_duplicates() {
        let dir = TempDir::new().unwrap();
        let store = safe_store(dir.path());

        store
            .populate(pairs([
                ("k", "v1"),
                ("other", "x"),
                ("k", "v2"),
                ("k", "v3"),
            ]))
            .unwrap();

        assert!(store.delete("k").unwrap());
        assert_eq!(store.dump().unwrap(), pairs([("other", "x")]));
    }

    #[test]
    fn test_delete_middle_record_swaps_with_last() {
        let dir = TempDir::new().unwrap();
        let store = safe_store(dir.path());

        store
            .populate(pairs([
                ("k0", "v"),
                ("k1", "v"),
                ("k2", "v"),
                ("k3", "v"),
                ("k4", "v"),
                ("k5", "v"),
                ("k6", "v"),
                ("k7", "v"),
                ("k8", "v"),
                ("k9", "v"),
            ]))
            .unwrap();

        assert!(store.delete("k4").unwrap());

        // k9 takes k4's slot; the rest stays put.
        assert_eq!(
            store.dump().unwrap(),
            pairs([
                ("k0", "v"),
                ("k1", "v"),
                ("k2", "v"),
                ("k3", "v"),
                ("k9", "v"),
                ("k5", "v"),
                ("k6", "v"),
                ("k7", "v"),
                ("k8", "v"),
            ])
        );
    }

    #[test]
    fn test_delete_nonexistent_key_returns_false() {
        let dir = TempDir::new().unwrap();
        let store = safe_store(dir.path());
        store.insert("k1", "v1").unwrap();

        assert!(!store.delete("missing").unwrap());
        assert_eq!(store.len().unwrap(), 1);
    }

    #[test]
    fn test_clear_empties_store() {
        let dir = TempDir::new().unwrap();
        let store = safe_store(dir.path());

        store.insert("key", "value").unwrap();
        store.clear().unwrap();
        assert_eq!(store.read("key").unwrap(), None);
    }

    #[test]
    fn test_dump_returns_all_records_with_duplicates() {
        let dir = TempDir::new().unwrap();
        let store = safe_store(dir.path());

        let records =
            pairs([("key", "val1"), ("key", "val2"), ("key", "val3")]);
        store.populate(records.clone()).unwrap();

        assert_eq!(store.dump().unwrap(), records);
        assert_eq!(
            store.entries().unwrap().get("key"),
            Some(&"val3".to_string())
        );
    }

    #[test]
    fn test_populate_round_trips_with_dump() {
        let dir = TempDir::new().unwrap();
        let store = safe_store(dir.path());

        let records =
            pairs([("a", "1"), ("b", "2"), ("a", "3"), ("c", "4"), ("b", "5")]);
        store.populate(records.clone()).unwrap();
        assert_eq!(store.dump().unwrap(), records);
    }

    #[test]
    fn test_populate_truncates_prior_contents() {
        let dir = TempDir::new().unwrap();
        let store = safe_store(dir.path());

        store.append("old1", "v").unwrap();
        store.append("old2", "v").unwrap();
        store.append("old3", "v").unwrap();
        assert_eq!(store.len().unwrap(), 3);

        store.populate(pairs([("new", "only")])).unwrap();
        assert_eq!(store.dump().unwrap(), pairs([("new", "only")]));
    }

    #[test]
    fn test_populate_empty_clears_store() {
        let dir = TempDir::new().unwrap();
        let store = safe_store(dir.path());

        store.append("k", "v").unwrap();
        store.populate(Vec::<(String, String)>::new()).unwrap();
        assert!(store.is_empty().unwrap());
    }

    #[test]
    fn test_populate_validates_before_writing() {
        let dir = TempDir::new().unwrap();
        let store = safe_store(dir.path());
        store.populate(pairs([("keep", "me")])).unwrap();

        // Bad record mid-batch: file must be untouched on rejection.
        let bad_value = "v".repeat(1023);
        let err = store
            .populate(vec![
                ("a".to_string(), "1".to_string()),
                ("b".to_string(), bad_value),
                ("c".to_string(), "3".to_string()),
            ])
            .unwrap_err();
        assert!(matches!(err, KvpError::ValueTooLarge { .. }));

        assert_eq!(store.dump().unwrap(), pairs([("keep", "me")]));
    }

    #[test]
    fn test_populate_enforces_unique_key_cap() {
        let dir = TempDir::new().unwrap();
        let store = safe_store(dir.path());

        let too_many: Vec<(String, String)> = (0..MAX_UNIQUE_KEYS + 1)
            .map(|i| (format!("k{i}"), "v".to_string()))
            .collect();
        let err = store.populate(too_many).unwrap_err();
        assert!(matches!(err, KvpError::MaxUniqueKeysExceeded { .. }));

        // Cap is checked pre-lock; the file is never opened.
        assert!(!store.path().exists());
    }

    #[test]
    fn test_populate_cap_counts_unique_keys_not_records() {
        let dir = TempDir::new().unwrap();
        let store = safe_store(dir.path());

        // 2 * MAX_UNIQUE_KEYS records, MAX_UNIQUE_KEYS unique keys.
        let mut records: Vec<(String, String)> = (0..MAX_UNIQUE_KEYS)
            .map(|i| (format!("k{i}"), "a".to_string()))
            .collect();
        records.extend(
            (0..MAX_UNIQUE_KEYS).map(|i| (format!("k{i}"), "b".to_string())),
        );

        store.populate(records).unwrap();
        assert_eq!(store.len().unwrap(), 2 * MAX_UNIQUE_KEYS);
    }

    #[test]
    fn test_populate_then_insert_respects_cap() {
        let dir = TempDir::new().unwrap();
        let store = safe_store(dir.path());

        let records: Vec<(String, String)> = (0..MAX_UNIQUE_KEYS)
            .map(|i| (format!("k{i}"), "v".to_string()))
            .collect();
        store.populate(records).unwrap();

        let err = store.insert("overflow", "v").unwrap_err();
        assert!(matches!(err, KvpError::MaxUniqueKeysExceeded { .. }));

        // Overwriting an existing key at the cap still works.
        store.insert("k0", "updated").unwrap();
        assert_eq!(store.read("k0").unwrap(), Some("updated".to_string()));
    }

    #[test]
    fn test_len_and_is_empty() {
        let dir = TempDir::new().unwrap();
        let store = safe_store(dir.path());

        assert!(store.is_empty().unwrap());
        assert_eq!(store.len().unwrap(), 0);

        store.insert("key", "value").unwrap();
        assert!(!store.is_empty().unwrap());
        assert_eq!(store.len().unwrap(), 1);

        store.insert("key2", "value2").unwrap();
        assert_eq!(store.len().unwrap(), 2);

        store.insert("key", "updated").unwrap();
        assert_eq!(store.len().unwrap(), 2);
    }

    #[test]
    fn test_is_stale_and_is_stale_at_boot_helpers() {
        let dir = TempDir::new().unwrap();
        let store = safe_store(dir.path());
        store.insert("key", "value").unwrap();

        assert!(!store.is_stale().unwrap());
        assert!(store.is_stale_at_boot(i64::MAX).unwrap());
        assert!(!store.is_stale_at_boot(0).unwrap());
    }

    #[test]
    fn test_clear_if_stale_clears_stale_data() {
        let dir = TempDir::new().unwrap();
        let store = safe_store(dir.path());
        store.insert("key", "value").unwrap();
        assert!(!store.is_empty().unwrap());

        set_mtime_to_epoch(store.path());
        assert!(store.is_stale().unwrap());

        store.clear_if_stale().unwrap();
        assert!(store.is_empty().unwrap());
    }

    #[rstest]
    #[case::ok(
        "cpu  1 2 3 4\nbtime 1710000000\nintr 1\n",
        Ok(1710000000)
    )]
    #[case::missing("cpu  1 2 3 4\n", Err(ErrorKind::NotFound))]
    #[case::invalid("btime not-a-number\n", Err(ErrorKind::InvalidData))]
    fn test_parse_proc_stat_btime_cases(
        #[case] contents: &str,
        #[case] expected: Result<i64, ErrorKind>,
    ) {
        match (parse_proc_stat_btime(contents), expected) {
            (Ok(v), Ok(e)) => assert_eq!(v, e),
            (Err(err), Err(kind)) => assert_eq!(err.kind(), kind),
            (got, want) => panic!("mismatch got={got:?} want={want:?}"),
        }
    }

    /// Round-trip cases for `encode_record`/`decode_record`.
    #[rstest]
    #[case::short("hello", "world")]
    #[case::empty_value("key", "")]
    fn test_encode_decode_round_trip(
        #[case] key: &str,
        #[case] value: &str,
    ) {
        let record = encode_record(key, value);
        assert_eq!(record.len(), RECORD_SIZE);
        let (k, v) = decode_record(&record).unwrap();
        assert_eq!(k, key);
        assert_eq!(v, value);
    }

    #[test]
    fn test_encode_decode_max_length_key() {
        let key = "x".repeat(WIRE_MAX_KEY_BYTES);
        let record = encode_record(&key, "val");
        let (k, v) = decode_record(&record).unwrap();
        assert_eq!(k, key);
        assert_eq!(v, "val");
    }

    /// Malformed buffers fed to `decode_record` produce the expected
    /// I/O error kind.
    #[rstest]
    #[case::wrong_size(vec![0u8; RECORD_SIZE + 1], ErrorKind::Other)]
    #[case::invalid_utf8_key({
        let mut b = vec![0u8; RECORD_SIZE];
        b[0] = 0xFF;
        b[1] = 0xFE;
        b
    }, ErrorKind::InvalidData)]
    #[case::invalid_utf8_value({
        let mut b = vec![0u8; RECORD_SIZE];
        b[WIRE_MAX_KEY_BYTES] = 0xFF;
        b[WIRE_MAX_KEY_BYTES + 1] = 0xFE;
        b
    }, ErrorKind::InvalidData)]
    fn test_decode_record_errors(
        #[case] buf: Vec<u8>,
        #[case] kind: ErrorKind,
    ) {
        let err = decode_record(&buf).unwrap_err();
        assert_eq!(err.kind(), kind);
    }

    #[test]
    fn test_iter_yields_all_records_in_order() {
        let dir = TempDir::new().unwrap();
        let store = safe_store(dir.path());

        let expected =
            pairs([("a", "1"), ("b", "2"), ("c", "3"), ("d", "4"), ("e", "5")]);
        store.populate(expected.clone()).unwrap();

        let iter = store.iter().unwrap();
        assert_eq!(iter.record_count(), 5);

        let records: Vec<(String, String)> = iter.map(|r| r.unwrap()).collect();
        assert_eq!(records, expected);
    }

    #[test]
    fn test_iter_empty_file() {
        let dir = TempDir::new().unwrap();
        let store = safe_store(dir.path());
        File::create(store.path()).unwrap();

        let iter = store.iter().unwrap();
        assert_eq!(iter.record_count(), 0);
        assert_eq!(iter.count(), 0);
    }

    #[test]
    fn test_iter_malformed_file_error() {
        let dir = TempDir::new().unwrap();
        let store = safe_store(dir.path());
        std::fs::write(store.path(), [0u8; RECORD_SIZE + 1]).unwrap();

        let err = store.iter().unwrap_err();
        assert!(matches!(err, KvpError::Io(_)));
    }

    #[test]
    fn test_len_malformed_file_error() {
        let dir = TempDir::new().unwrap();
        let store = safe_store(dir.path());
        std::fs::write(store.path(), [0u8; RECORD_SIZE + 1]).unwrap();

        let err = store.len().unwrap_err();
        assert!(matches!(err, KvpError::Io(_)));
        let err = store.is_empty().unwrap_err();
        assert!(matches!(err, KvpError::Io(_)));
    }

    #[test]
    fn test_iter_drop_mid_iteration_releases_lock() {
        let dir = TempDir::new().unwrap();
        let store = safe_store(dir.path());
        store.populate(pairs([("k1", "v1"), ("k2", "v2")])).unwrap();

        {
            let mut iter = store.iter().unwrap();
            iter.next().unwrap().unwrap();
        }

        store.insert("k3", "v3").unwrap();
        assert_eq!(store.len().unwrap(), 3);
    }

    #[test]
    fn test_overwrite_adjacent_records_untouched() {
        let dir = TempDir::new().unwrap();
        let store = safe_store(dir.path());
        store
            .populate(pairs([
                ("first", "val_first"),
                ("middle", "val_middle"),
                ("last", "val_last"),
            ]))
            .unwrap();

        let raw_before = std::fs::read(store.path()).unwrap();
        let first_before = &raw_before[..RECORD_SIZE];
        let last_before = &raw_before[2 * RECORD_SIZE..3 * RECORD_SIZE];

        {
            let mut iter = store.iter_mut().unwrap();
            iter.next().unwrap().unwrap();
            let (k, _) = iter.next().unwrap().unwrap();
            assert_eq!(k, "middle");
            iter.overwrite_current_value("UPDATED").unwrap();
            iter.flush().unwrap();
        }

        let raw_after = std::fs::read(store.path()).unwrap();
        assert_eq!(&raw_after[..RECORD_SIZE], first_before);
        assert_eq!(&raw_after[2 * RECORD_SIZE..3 * RECORD_SIZE], last_before);

        assert_eq!(
            store.dump().unwrap(),
            pairs([
                ("first", "val_first"),
                ("middle", "UPDATED"),
                ("last", "val_last"),
            ])
        );
    }

    #[test]
    fn test_overwrite_multiple_in_one_pass() {
        let dir = TempDir::new().unwrap();
        let store = safe_store(dir.path());
        store
            .populate(pairs([("a", "old_a"), ("b", "old_b"), ("c", "old_c")]))
            .unwrap();

        {
            let mut iter = store.iter_mut().unwrap();
            let mut idx = 0;
            while let Some(record) = iter.next() {
                record.unwrap();
                if idx == 0 || idx == 2 {
                    iter.overwrite_current_value("new").unwrap();
                }
                idx += 1;
            }
            iter.flush().unwrap();
        }

        assert_eq!(
            store.dump().unwrap(),
            pairs([("a", "new"), ("b", "old_b"), ("c", "new")])
        );
    }

    #[test]
    fn test_overwrite_before_next_errors() {
        let dir = TempDir::new().unwrap();
        let store = safe_store(dir.path());
        store.append("k", "v").unwrap();

        let mut iter = store.iter_mut().unwrap();
        let err = iter.overwrite_current_value("new").unwrap_err();
        assert_eq!(err.kind(), ErrorKind::InvalidInput);
    }

    #[test]
    fn test_remove_before_next_errors() {
        let dir = TempDir::new().unwrap();
        let store = safe_store(dir.path());
        store.append("k", "v").unwrap();

        let mut iter = store.iter_mut().unwrap();
        let err = iter.remove_current().unwrap_err();
        assert_eq!(err.kind(), ErrorKind::InvalidInput);
    }

    #[test]
    fn test_remove_swap_and_continue() {
        let dir = TempDir::new().unwrap();
        let store = safe_store(dir.path());
        store
            .populate(pairs([("A", "1"), ("B", "2"), ("C", "3"), ("D", "4")]))
            .unwrap();

        let mut collected = Vec::new();
        {
            let mut iter = store.iter_mut().unwrap();
            while let Some(record) = iter.next() {
                let (k, v) = record.unwrap();
                if k == "B" {
                    iter.remove_current().unwrap();
                } else {
                    collected.push((k, v));
                }
            }
            iter.flush().unwrap();
        }

        assert_eq!(collected.len(), 3);
        assert!(collected.iter().any(|(k, _)| k == "A"));
        assert!(collected.iter().any(|(k, _)| k == "C"));
        assert!(collected.iter().any(|(k, _)| k == "D"));

        assert_eq!(store.len().unwrap(), 3);
        assert_eq!(store.read("B").unwrap(), None);
    }

    #[test]
    fn test_remove_last_record_no_swap() {
        let dir = TempDir::new().unwrap();
        let store = safe_store(dir.path());
        store
            .populate(pairs([("a", "1"), ("b", "2"), ("c", "3")]))
            .unwrap();

        {
            let mut iter = store.iter_mut().unwrap();
            iter.next().unwrap().unwrap();
            iter.next().unwrap().unwrap();
            iter.next().unwrap().unwrap();
            iter.remove_current().unwrap();
            iter.flush().unwrap();
        }

        assert_eq!(store.len().unwrap(), 2);
        assert_eq!(store.read("c").unwrap(), None);
        assert_eq!(store.read("a").unwrap(), Some("1".to_string()));
        assert_eq!(store.read("b").unwrap(), Some("2".to_string()));
    }

    #[test]
    fn test_remove_only_record() {
        let dir = TempDir::new().unwrap();
        let store = safe_store(dir.path());
        store.append("solo", "val").unwrap();

        {
            let mut iter = store.iter_mut().unwrap();
            iter.next().unwrap().unwrap();
            iter.remove_current().unwrap();
            iter.flush().unwrap();
        }

        assert!(store.is_empty().unwrap());
    }

    #[test]
    fn test_append_after_remove_with_swap_preserves_iteration_position() {
        let dir = TempDir::new().unwrap();
        let store = safe_store(dir.path());
        store
            .populate(pairs([("A", "1"), ("B", "2"), ("C", "3")]))
            .unwrap();

        let remaining = {
            let mut iter = store.iter_mut().unwrap();
            let (k, _) = iter.next().unwrap().unwrap();
            assert_eq!(k, "A");
            iter.remove_current().unwrap();
            iter.append("D", "4").unwrap();

            let mut records = Vec::new();
            for record in iter.by_ref() {
                records.push(record.unwrap());
            }
            iter.flush().unwrap();
            records
        };

        assert_eq!(remaining, pairs([("C", "3"), ("B", "2"), ("D", "4")]));
    }

    #[test]
    fn test_file_integrity_after_mixed_ops() {
        let dir = TempDir::new().unwrap();
        let store = safe_store(dir.path());

        for i in 0..10 {
            store.insert(&format!("u{i}"), &format!("uv{i}")).unwrap();
        }
        for i in 0..5 {
            store.append(&format!("a{i}"), &format!("av{i}")).unwrap();
        }
        store.delete("u3").unwrap();
        store.delete("u7").unwrap();
        store.insert("u0", "overwritten").unwrap();

        let raw = std::fs::read(store.path()).unwrap();
        assert_eq!(raw.len() % RECORD_SIZE, 0);

        let record_count = raw.len() / RECORD_SIZE;
        for i in 0..record_count {
            let start = i * RECORD_SIZE;
            let end = start + RECORD_SIZE;
            decode_record(&raw[start..end]).unwrap();
        }
    }

    #[test]
    fn test_kvp_error_display() {
        let cases: Vec<(KvpError, &str)> = vec![
            (KvpError::EmptyKey, "KVP key must not be empty"),
            (
                KvpError::Io(io::Error::new(ErrorKind::NotFound, "gone")),
                "gone",
            ),
            (
                KvpError::KeyContainsNull,
                "KVP key must not contain null bytes",
            ),
            (
                KvpError::KeyTooLarge {
                    max: 254,
                    actual: 300,
                },
                "KVP key length (300) exceeds maximum (254)",
            ),
            (
                KvpError::MaxUniqueKeysExceeded { max: 1024 },
                "KVP unique key count exceeded maximum (1024)",
            ),
            (
                KvpError::ValueTooLarge {
                    max: 1022,
                    actual: 2000,
                },
                "KVP value length (2000) exceeds maximum (1022)",
            ),
            (
                KvpError::ValueContainsNull,
                "KVP value must not contain null bytes",
            ),
        ];
        for (err, expected) in cases {
            assert_eq!(err.to_string(), expected);
        }
    }

    #[test]
    fn test_kvp_error_source() {
        let io_err = KvpError::Io(io::Error::other("kvp-error-source"));
        assert!(io_err.source().is_some());

        assert!(KvpError::EmptyKey.source().is_none());
        assert!(KvpError::KeyContainsNull.source().is_none());
        assert!(KvpError::ValueContainsNull.source().is_none());
    }

    #[test]
    fn test_kvp_error_from_io() {
        let io_err = io::Error::new(ErrorKind::PermissionDenied, "denied");
        let kvp_err: KvpError = io_err.into();
        assert!(matches!(kvp_err, KvpError::Io(_)));
        assert_eq!(kvp_err.to_string(), "denied");
    }

    #[test]
    fn test_concurrent_inserts_to_different_keys() {
        let dir = TempDir::new().unwrap();
        let dir_path = dir.path().to_path_buf();
        let threads: Vec<_> = (0..8)
            .map(|t| {
                let d = dir_path.clone();
                std::thread::spawn(move || {
                    let store =
                        KvpPoolStore::new_in(KvpPool::Guest, d, PoolMode::Safe)
                            .unwrap();
                    for i in 0..10 {
                        let key = format!("t{t}_k{i}");
                        store.insert(&key, &format!("val_{t}_{i}")).unwrap();
                    }
                })
            })
            .collect();

        for t in threads {
            t.join().unwrap();
        }

        let store = safe_store(dir.path());
        let entries = store.entries().unwrap();
        assert_eq!(entries.len(), 80);
        for t in 0..8 {
            for i in 0..10 {
                let key = format!("t{t}_k{i}");
                assert_eq!(entries.get(&key), Some(&format!("val_{t}_{i}")));
            }
        }
    }

    #[test]
    fn test_concurrent_inserts_to_same_key() {
        let dir = TempDir::new().unwrap();
        let dir_path = dir.path().to_path_buf();
        let threads: Vec<_> = (0..8)
            .map(|t| {
                let d = dir_path.clone();
                std::thread::spawn(move || {
                    let store =
                        KvpPoolStore::new_in(KvpPool::Guest, d, PoolMode::Safe)
                            .unwrap();
                    for i in 0..10 {
                        store
                            .insert("shared_key", &format!("t{t}_v{i}"))
                            .unwrap();
                    }
                })
            })
            .collect();

        for t in threads {
            t.join().unwrap();
        }

        let store = safe_store(dir.path());
        assert_eq!(store.len().unwrap(), 1);
        let val = store.read("shared_key").unwrap().unwrap();
        assert!(val.starts_with('t') && val.contains("_v"));

        let file_len = std::fs::metadata(store.path()).unwrap().len() as usize;
        assert_eq!(file_len, RECORD_SIZE);
    }

    #[test]
    fn test_concurrent_appends() {
        let dir = TempDir::new().unwrap();
        let dir_path = dir.path().to_path_buf();

        let threads: Vec<_> = (0..8)
            .map(|t| {
                let d = dir_path.clone();
                std::thread::spawn(move || {
                    let store =
                        KvpPoolStore::new_in(KvpPool::Guest, d, PoolMode::Safe)
                            .unwrap();
                    for i in 0..10 {
                        store
                            .append(
                                &format!("t{t}_d{i}"),
                                &format!("data_{t}_{i}"),
                            )
                            .unwrap();
                    }
                })
            })
            .collect();

        for t in threads {
            t.join().unwrap();
        }

        let store = safe_store(dir.path());
        assert_eq!(store.len().unwrap(), 80);

        let entries = store.entries().unwrap();
        for t in 0..8 {
            for i in 0..10 {
                let key = format!("t{t}_d{i}");
                assert!(entries.contains_key(&key), "missing key {key}");
            }
        }
    }

    #[test]
    fn test_concurrent_writers_at_key_cap() {
        let dir = TempDir::new().unwrap();
        let dir_path = dir.path().to_path_buf();

        let store = safe_store(dir.path());
        prepopulate(&store, MAX_UNIQUE_KEYS - 4);

        let threads: Vec<_> = (0..4)
            .map(|t| {
                let d = dir_path.clone();
                std::thread::spawn(move || {
                    let store =
                        KvpPoolStore::new_in(KvpPool::Guest, d, PoolMode::Safe)
                            .unwrap();
                    store.insert(&format!("new{t}"), "v")
                })
            })
            .collect();

        let results: Vec<_> =
            threads.into_iter().map(|t| t.join().unwrap()).collect();

        let successes = results.iter().filter(|r| r.is_ok()).count();
        let cap_errors = results
            .iter()
            .filter(|r| {
                matches!(r, Err(KvpError::MaxUniqueKeysExceeded { .. }))
            })
            .count();

        assert_eq!(successes, 4);
        assert_eq!(cap_errors, 0);
        assert_eq!(store.len().unwrap(), MAX_UNIQUE_KEYS);

        let err = store.insert("one_too_many", "v").unwrap_err();
        assert!(matches!(err, KvpError::MaxUniqueKeysExceeded { .. }));
    }

    #[test]
    fn test_concurrent_readers_only() {
        let dir = TempDir::new().unwrap();
        let store = safe_store(dir.path());
        for i in 0..10 {
            store.insert(&format!("k{i}"), &format!("v{i}")).unwrap();
        }

        let dir_path = dir.path().to_path_buf();
        let threads: Vec<_> = (0..8)
            .map(|_| {
                let d = dir_path.clone();
                std::thread::spawn(move || {
                    let store =
                        KvpPoolStore::new_in(KvpPool::Guest, d, PoolMode::Safe)
                            .unwrap();
                    for _ in 0..20 {
                        let entries = store.entries().unwrap();
                        assert_eq!(entries.len(), 10);
                        for i in 0..10 {
                            assert_eq!(
                                store.read(&format!("k{i}")).unwrap(),
                                Some(format!("v{i}"))
                            );
                        }
                    }
                })
            })
            .collect();

        for t in threads {
            t.join().unwrap();
        }
    }

    #[test]
    fn test_concurrent_readers_and_writers() {
        let dir = TempDir::new().unwrap();
        let dir_path = dir.path().to_path_buf();

        let store = safe_store(dir.path());
        for i in 0..10 {
            store.insert(&format!("k{i}"), &format!("v{i}")).unwrap();
        }

        let writer_threads: Vec<_> = (0..4)
            .map(|t| {
                let d = dir_path.clone();
                std::thread::spawn(move || {
                    let store =
                        KvpPoolStore::new_in(KvpPool::Guest, d, PoolMode::Safe)
                            .unwrap();
                    for round in 0..5 {
                        let key = format!("k{t}");
                        store.insert(&key, &format!("w{t}_r{round}")).unwrap();
                    }
                })
            })
            .collect();

        let reader_threads: Vec<_> = (0..4)
            .map(|_| {
                let d = dir_path.clone();
                std::thread::spawn(move || {
                    let store =
                        KvpPoolStore::new_in(KvpPool::Guest, d, PoolMode::Safe)
                            .unwrap();
                    for _ in 0..20 {
                        let entries = store.entries().unwrap();
                        assert!(entries.len() <= 10);
                        for (k, v) in &entries {
                            assert!(!k.is_empty());
                            assert!(!v.is_empty());
                        }
                    }
                })
            })
            .collect();

        for t in writer_threads {
            t.join().unwrap();
        }
        for t in reader_threads {
            t.join().unwrap();
        }

        let entries = store.entries().unwrap();
        assert_eq!(entries.len(), 10);
    }

    #[test]
    fn test_concurrent_mixed_insert_and_append() {
        let dir = TempDir::new().unwrap();
        let dir_path = dir.path().to_path_buf();

        let store = safe_store(dir.path());
        for i in 0..4 {
            store.insert(&format!("fixed{i}"), "init").unwrap();
        }

        let insert_threads: Vec<_> = (0..4)
            .map(|t| {
                let d = dir_path.clone();
                std::thread::spawn(move || {
                    let store =
                        KvpPoolStore::new_in(KvpPool::Guest, d, PoolMode::Safe)
                            .unwrap();
                    for round in 0..5 {
                        store
                            .insert(&format!("fixed{t}"), &format!("r{round}"))
                            .unwrap();
                    }
                })
            })
            .collect();

        let append_threads: Vec<_> = (0..4)
            .map(|t| {
                let d = dir_path.clone();
                std::thread::spawn(move || {
                    let store =
                        KvpPoolStore::new_in(KvpPool::Guest, d, PoolMode::Safe)
                            .unwrap();
                    for i in 0..5 {
                        store
                            .append(
                                &format!("diag_t{t}_i{i}"),
                                &format!("d{i}"),
                            )
                            .unwrap();
                    }
                })
            })
            .collect();

        for t in insert_threads {
            t.join().unwrap();
        }
        for t in append_threads {
            t.join().unwrap();
        }

        let entries = store.entries().unwrap();
        assert_eq!(entries.len(), 24);
        for t in 0..4 {
            assert!(entries.contains_key(&format!("fixed{t}")));
        }
    }

    #[derive(Clone, Copy)]
    enum StoreOp {
        Read,
        Delete,
        Clear,
        ClearIfStale,
        Entries,
        Dump,
        Populate,
        Len,
        IsStale,
        IsStaleAtBoot,
        Insert,
        Append,
    }

    /// Every fallible read/write op surfaces an unreachable directory
    /// as [`KvpError::Io`].
    #[rstest]
    #[case::read(StoreOp::Read)]
    #[case::delete(StoreOp::Delete)]
    #[case::clear(StoreOp::Clear)]
    #[case::clear_if_stale(StoreOp::ClearIfStale)]
    #[case::entries(StoreOp::Entries)]
    #[case::dump(StoreOp::Dump)]
    #[case::populate(StoreOp::Populate)]
    #[case::len(StoreOp::Len)]
    #[case::is_stale(StoreOp::IsStale)]
    #[case::is_stale_at_boot(StoreOp::IsStaleAtBoot)]
    #[case::insert(StoreOp::Insert)]
    #[case::append(StoreOp::Append)]
    fn test_permission_denied(#[case] op: StoreOp) {
        let dir = TempDir::new().unwrap();
        let store = safe_store(dir.path());
        store.insert("k", "v").unwrap();

        lock_dir(dir.path());
        let result: Result<(), KvpError> = match op {
            StoreOp::Read => store.read("k").map(|_| ()),
            StoreOp::Delete => store.delete("k").map(|_| ()),
            StoreOp::Clear => store.clear(),
            StoreOp::ClearIfStale => store.clear_if_stale(),
            StoreOp::Entries => store.entries().map(|_| ()),
            StoreOp::Dump => store.dump().map(|_| ()),
            StoreOp::Populate => store.populate(pairs([("a", "b")])),
            StoreOp::Len => store.len().map(|_| ()),
            StoreOp::IsStale => store.is_stale().map(|_| ()),
            StoreOp::IsStaleAtBoot => {
                store.is_stale_at_boot(i64::MAX).map(|_| ())
            }
            StoreOp::Insert => store.insert("k2", "v2"),
            StoreOp::Append => store.append("k", "v"),
        };
        unlock_dir(dir.path());
        assert!(matches!(result.unwrap_err(), KvpError::Io(_)));
    }

    /// F_WRLCK needs a writable fd; read-only fd returns EBADF.
    #[test]
    fn test_fcntl_lock_exclusive_fails_on_read_only_fd() {
        let tmp = NamedTempFile::new().unwrap();
        let file = OpenOptions::new().read(true).open(tmp.path()).unwrap();
        let err = fcntl_lock_exclusive(&file).unwrap_err();
        assert!(err.to_string().contains("failed to fcntl-lock KVP file"));
    }

    /// F_RDLCK needs a readable fd; write-only fd returns EBADF.
    #[test]
    fn test_fcntl_lock_shared_fails_on_write_only_fd() {
        let tmp = NamedTempFile::new().unwrap();
        let file = OpenOptions::new().write(true).open(tmp.path()).unwrap();
        let err = fcntl_lock_shared(&file).unwrap_err();
        assert!(err.to_string().contains("failed to fcntl-lock KVP file"));
    }

    /// Cleanup branch in `lock_for_writing`: when fcntl fails after
    /// flock succeeded, the held flock must be released. Read-only fd
    /// makes fcntl(F_WRLCK) fail with EBADF, then a non-blocking flock
    /// from a separate fd verifies the lock was actually released.
    #[test]
    fn test_lock_for_writing_releases_flock_when_fcntl_fails() {
        let tmp = NamedTempFile::new().unwrap();
        let file = OpenOptions::new().read(true).open(tmp.path()).unwrap();
        let err = lock_for_writing(&file).unwrap_err();
        assert!(err.to_string().contains("failed to fcntl-lock KVP file"));

        let other = OpenOptions::new().read(true).open(tmp.path()).unwrap();
        let rc = unsafe {
            libc::flock(other.as_raw_fd(), libc::LOCK_EX | libc::LOCK_NB)
        };
        assert_eq!(rc, 0, "flock should have been released by cleanup");
    }

    /// Symmetric cleanup branch in `lock_for_reading`: write-only fd
    /// makes fcntl(F_RDLCK) fail with EBADF.
    #[test]
    fn test_lock_for_reading_releases_flock_when_fcntl_fails() {
        let tmp = NamedTempFile::new().unwrap();
        let file = OpenOptions::new().write(true).open(tmp.path()).unwrap();
        let err = lock_for_reading(&file).unwrap_err();
        assert!(err.to_string().contains("failed to fcntl-lock KVP file"));

        let other = OpenOptions::new().read(true).open(tmp.path()).unwrap();
        let rc = unsafe {
            libc::flock(other.as_raw_fd(), libc::LOCK_EX | libc::LOCK_NB)
        };
        assert_eq!(rc, 0, "flock should have been released by cleanup");
    }

    /// Error branches in the three `flock(2)` wrappers. `flock` is
    /// hard to fail since it works on any open fd, so we close an fd
    /// and reconstitute a `File` wrapping it — subsequent `flock`
    /// calls return EBADF. The `File` is `mem::forget`-ed to avoid
    /// the drop trying to close an already-closed (possibly reused)
    /// fd.
    #[rstest]
    #[case::lock_ex(
        flock_lock_exclusive as fn(&File) -> io::Result<()>,
        "failed to flock KVP file"
    )]
    #[case::lock_sh(flock_lock_shared, "failed to flock KVP file")]
    #[case::unlock(flock_unlock, "failed to flock-unlock KVP file")]
    fn test_flock_op_fails_on_closed_fd(
        #[case] op: fn(&File) -> io::Result<()>,
        #[case] expected_msg: &str,
    ) {
        use std::os::unix::io::{FromRawFd, IntoRawFd};
        let tmp = NamedTempFile::new().unwrap();
        let f = std::fs::File::open(tmp.path()).unwrap();
        let raw_fd = f.into_raw_fd();
        assert_eq!(unsafe { libc::close(raw_fd) }, 0);
        let file = unsafe { File::from_raw_fd(raw_fd) };
        let err = op(&file).unwrap_err();
        assert!(err.to_string().contains(expected_msg), "got: {err}");
        std::mem::forget(file);
    }

    /// A FIFO at the pool path forces specific I/O errors from each op:
    /// `ftruncate` returns EINVAL, `lseek` returns ESPIPE.
    #[rstest]
    #[case::clear(FifoOp::Clear, libc::EINVAL)]
    #[case::append(FifoOp::Append, libc::ESPIPE)]
    #[case::populate(FifoOp::Populate, libc::ESPIPE)]
    fn test_fifo_propagates_io_error(
        #[case] op: FifoOp,
        #[case] expected_errno: i32,
    ) {
        let dir = TempDir::new().unwrap();
        let store = safe_store(dir.path());
        make_fifo_at(store.path());

        let err = match op {
            FifoOp::Clear => store.clear().unwrap_err(),
            FifoOp::Append => store.append("k", "v").unwrap_err(),
            FifoOp::Populate => store.populate(pairs([("k", "v")])).unwrap_err(),
        };
        assert!(
            matches!(err, KvpError::Io(ref e) if e.raw_os_error() == Some(expected_errno)),
            "got: {err:?}"
        );
    }

    #[test]
    fn test_size_hint_tracks_iteration() {
        let dir = TempDir::new().unwrap();
        let store = safe_store(dir.path());
        store
            .populate(pairs([("a", "1"), ("b", "2"), ("c", "3")]))
            .unwrap();

        let mut iter = store.iter().unwrap();
        assert_eq!(iter.size_hint(), (3, Some(3)));

        iter.next().unwrap().unwrap();
        assert_eq!(iter.size_hint(), (2, Some(2)));

        iter.next().unwrap().unwrap();
        assert_eq!(iter.size_hint(), (1, Some(1)));

        iter.next().unwrap().unwrap();
        assert_eq!(iter.size_hint(), (0, Some(0)));

        assert!(iter.next().is_none());
    }

    /// Covers the `Err(e) => Some(Err(e))` branch in `Iterator::next`
    /// by truncating the file after the iterator caches its record count.
    #[test]
    fn test_iter_read_error_on_truncated_file() {
        let dir = TempDir::new().unwrap();
        let store = safe_store(dir.path());
        store.populate(pairs([("a", "1"), ("b", "2")])).unwrap();

        // Open a mutable iterator (exclusive lock) so we can manipulate the file.
        let mut iter = store.iter_mut().unwrap();
        assert_eq!(iter.record_count(), 2);

        // Read the first record successfully.
        let (k, _) = iter.next().unwrap().unwrap();
        assert_eq!(k, "a");

        // Truncate via the iterator's own file to remove the second record.
        // The iterator still thinks record_count == 2, so the next
        // read_exact will hit an unexpected EOF.
        iter.file.set_len(0).unwrap();

        // The iterator's cached record_count (2) > current_index (1),
        // so it attempts read_exact, which fails.
        let err = iter.next().unwrap().unwrap_err();
        assert_eq!(err.kind(), ErrorKind::UnexpectedEof);
    }
}
