name: "Run Clippy for Linting"
permissions:
  contents: read
on:
  pull_request:
    branches:
      - main
  schedule:
      - cron: '0 0 * * 0'

jobs:
  clippy:
    name: Run clippy on azure-init 
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      matrix:
        rust-toolchain: [stable, "1.88.0"]
    steps:
      - name: Install libudev
        run: |
          sudo apt update
          sudo apt install -y libudev-dev
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: dtolnay/rust-toolchain@7e38f4b43b4db5c8dd498af069a4f6196df1d067
        with:
          toolchain: ${{matrix.rust-toolchain}}
          components: clippy
      - name: Run clippy
        run: cargo clippy --locked --all-targets --all-features --verbose -- --deny warnings
